version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
  discard-paths: yes
